spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gravel-canvas/config-repo
          username: 709127705@qq.com
          password: 
          basedir: D:\JAVA\IDEA\SpringClour_sell\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
