spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gravel-canvas/config-repo
          username: 709127705@qq.com
          password: zzglxt520..
          basedir: D:\JAVA\IDEA\SpringClour_sell\config\basedir
  rabbitmq:
    host: 172.16.3.52
#    port: 5672
#    username: guest
#    password: guest
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"