spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/springcloud_sell?characterEncoding=utf-8&userSSL=false
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8761/eureka

# 客户端负载均衡(默认轮询)修改(随机)方法  规则结构 IRule
#PRODUCT:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.RandomRule